name: Claude AI Backend
description: All-in-one add-on - Automatically deploys Claude component + runs backend API for Claude AI Assistant
version: "2.0.2"
slug: claude-backend
image: "ghcr.io/Bobsilvio/claude-backend:{VERSION}"
init: true
arch:
  - aarch64
  - amd64
  - armv7
homeassistant: "2024.1.0"
host_network: false
host_dbus: false
ingress: true
ingress_port: 5000
ingress_entry: "/"
panel_icon: "mdi:robot"
panel_title: "Claude AI"
privileged:
  - NET_ADMIN
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Claude Backend API"
environment:
  DEBUG_MODE: "False"
options:

  claude_api_key: ""
  api_port: "5000"
  debug_mode: false
  polling_interval: "60"
  timeout: "30"
  max_retries: "3"
schema:
  claude_api_key: password
  api_port: str
  debug_mode: bool?
  polling_interval: str?
  timeout: str?
  max_retries: str?
documentation: "https://github.com/Bobsilvio/ha-claude"
support: "https://github.com/Bobsilvio/ha-claude/issues"
maintainers:
  - Bobsilvio
documentation: "https://github.com/Bobsilvio/ha-claude"
support: "https://github.com/Bobsilvio/ha-claude/issues"
maintainers:
  - Bobsilvio
